//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARR_MonthlyCollection
    {
        public int Collectedid { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> CollectedMonth { get; set; }
        public Nullable<decimal> CollectedAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string DeleteFlag { get; set; }
        public Nullable<decimal> LD { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> BC { get; set; }
        public Nullable<decimal> OD { get; set; }
        public Nullable<decimal> retention { get; set; }
        public Nullable<decimal> SD { get; set; }
        public Nullable<decimal> PBG { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
    }
}
