//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARR_MonthCollectionTarget
    {
        public int MonthCollectioId { get; set; }
        public string InvoiceNo { get; set; }
        public string WBSElement { get; set; }
        public Nullable<System.DateTime> CurrentMonth { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> SubmittedBY { get; set; }
        public Nullable<System.DateTime> Submittedon { get; set; }
        public string DeleteFlag { get; set; }
        public Nullable<int> fileno { get; set; }
    }
}
