//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARR_Master
    {
        public int id { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> osDate { get; set; }
        public string Division { get; set; }
        public string docno { get; set; }
        public Nullable<System.DateTime> postingdate { get; set; }
        public string salesoffice { get; set; }
        public string salesofficeName { get; set; }
        public string salesgroup { get; set; }
        public string SalesgroupName { get; set; }
        public string paymentterm { get; set; }
        public string paymenttermDescription { get; set; }
        public string sono { get; set; }
        public string pono { get; set; }
        public Nullable<System.DateTime> podate { get; set; }
        public string wbselement { get; set; }
        public string wbstext { get; set; }
        public string projectmgrid { get; set; }
        public string Projectmanager { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public Nullable<decimal> docinvoiceamount { get; set; }
        public string invoiceCurrancy { get; set; }
        public Nullable<decimal> inrinvoiceamount { get; set; }
        public Nullable<decimal> receiptamount { get; set; }
        public Nullable<decimal> tdsamount { get; set; }
        public Nullable<decimal> retentionamount { get; set; }
        public Nullable<decimal> outstandingamount { get; set; }
        public Nullable<decimal> notdue { get; set; }
        public Nullable<decimal> days1to30 { get; set; }
        public Nullable<decimal> days31to60 { get; set; }
        public Nullable<decimal> days61to90 { get; set; }
        public Nullable<decimal> days91to180 { get; set; }
        public Nullable<decimal> days366to730 { get; set; }
        public Nullable<decimal> above730days { get; set; }
        public Nullable<int> rowno { get; set; }
        public Nullable<int> Fileno { get; set; }
        public string Deleteflag { get; set; }
        public Nullable<decimal> days181to365 { get; set; }
        public string Region { get; set; }
        public string YilSono { get; set; }
        public Nullable<decimal> DocOutstandingAmount { get; set; }
        public string DocOSCurrency { get; set; }
        public Nullable<decimal> CollectedAmount { get; set; }
        public string Narration { get; set; }
        public Nullable<int> noofdays { get; set; }
        public Nullable<System.DateTime> NetDueDate { get; set; }
        public string JobCode { get; set; }
        public Nullable<decimal> Docreceiptamount { get; set; }
        public string DocreceiptamountCurrency { get; set; }
        public Nullable<decimal> days730to1095 { get; set; }
        public Nullable<decimal> days1095to1460 { get; set; }
        public Nullable<decimal> days1460to1825 { get; set; }
        public Nullable<decimal> days1825to2190 { get; set; }
        public Nullable<decimal> days2190to2555 { get; set; }
        public Nullable<decimal> Above2555Days { get; set; }
        public Nullable<decimal> Provision { get; set; }
    }
}
