//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARR_MonthlyCollectionTracking
    {
        public int id { get; set; }
        public Nullable<int> TrackId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> CollectedMonth { get; set; }
        public Nullable<decimal> CollectedAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string DeleteFlag { get; set; }
    }
}
