//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionDetail
    {
        public int CollectionDetailId { get; set; }
        public string DocumentNumber { get; set; }
        public string Lineitem { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string DocumentType { get; set; }
        public string PostingKey { get; set; }
        public string Account { get; set; }
        public string Accountname { get; set; }
        public string GLAccount { get; set; }
        public string Reference { get; set; }
        public Nullable<double> Amountindoccurr { get; set; }
        public string Documentcurrency { get; set; }
        public string Effexchangerate { get; set; }
        public Nullable<double> Amountinlocalcurrency { get; set; }
        public string LocalCurrency { get; set; }
        public string BusinessPlace { get; set; }
        public string Taxcode { get; set; }
        public string PurchasingDocument { get; set; }
        public string Item { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string FiscalYear { get; set; }
        public string Invoicereference { get; set; }
        public string ReferenceKey { get; set; }
        public Nullable<double> Wtaxexemptamount { get; set; }
        public Nullable<double> Withhldgtaxbaseamount { get; set; }
        public Nullable<double> Withholdingtaxamnt { get; set; }
        public string NoName { get; set; }
        public string AccountType { get; set; }
        public string Acctsrblepledind { get; set; }
        public string Alternativeaccountno { get; set; }
        public Nullable<double> Amountinloccurr2 { get; set; }
        public Nullable<double> Amtinloccurr3 { get; set; }
        public Nullable<double> Amtinpaymentcurrency { get; set; }
        public Nullable<double> Arrearsafternetduedate { get; set; }
        public Nullable<double> Arrearsfordiscount1 { get; set; }
        public string Asset { get; set; }
        public string Assignment { get; set; }
        public string BaseUnitofMeasure { get; set; }
        public Nullable<System.DateTime> BaselinePaymentDte { get; set; }
        public string BillExchangeUsage { get; set; }
        public string BillingDocument { get; set; }
        public string Branchaccount { get; set; }
        public string BusinessArea { get; set; }
        public string CaseID { get; set; }
        public Nullable<double> CashdiscamtLC { get; set; }
        public string Cashdisc1due { get; set; }
        public string Checknumberfrom { get; set; }
        public string Clearedopenitemssymbol { get; set; }
        public string Clearedopenitemssymbol1 { get; set; }
        public Nullable<System.DateTime> Clearingdate { get; set; }
        public string ClearingDocument { get; set; }
        public string ClearingFiscalYear { get; set; }
        public Nullable<double> Clearingitem { get; set; }
        public string Collectiveinvoice { get; set; }
        public string CompanyCode { get; set; }
        public string ContractNumber { get; set; }
        public string ContractType { get; set; }
        public string CostCenter { get; set; }
        public string Creditcontrolarea { get; set; }
        public string Creditcontrolareacurrency { get; set; }
        public Nullable<double> Currentcashdiscamount { get; set; }
        public string Customer { get; set; }
        public Nullable<double> Days1 { get; set; }
        public Nullable<double> Days2 { get; set; }
        public Nullable<double> Daysnet { get; set; }
        public string DebitCreditInd { get; set; }
        public string DirectDebitPrenotification { get; set; }
        public string Discount1duedatesymbol { get; set; }
        public Nullable<double> Discountamount { get; set; }
        public Nullable<double> Discountbaseamount { get; set; }
        public Nullable<double> DiscountPercent1 { get; set; }
        public Nullable<double> DiscountPercent2 { get; set; }
        public string Disputeditem { get; set; }
        public string Docstatus { get; set; }
        public string Documentarchived { get; set; }
        public string DocumentHeaderText { get; set; }
        public string Duenet { get; set; }
        public string DunningArea { get; set; }
        public string Dunningblock { get; set; }
        public string Dunningkey { get; set; }
        public string Dunninglevel { get; set; }
        public string Fixed { get; set; }
        public string FlowType { get; set; }
        public string Followondoctype { get; set; }
        public Nullable<double> Generalledgeramount { get; set; }
        public string Generalledgercurrency { get; set; }
        public Nullable<double> Hedgedamount { get; set; }
        public string HouseBank { get; set; }
        public string Instructionkey1 { get; set; }
        public string Instructionkey2 { get; set; }
        public string Instructionkey3 { get; set; }
        public string Instructionkey4 { get; set; }
        public Nullable<double> Intcalcnumerator { get; set; }
        public string Lastdunned { get; set; }
        public string LineitemID { get; set; }
        public string Localcurrency2 { get; set; }
        public string Localcurrency3 { get; set; }
        public string Mandate { get; set; }
        public string MandateReference { get; set; }
        public string MCARunID { get; set; }
        public string Name1 { get; set; }
        public string Negativeposting { get; set; }
        public Nullable<System.DateTime> Netduedate { get; set; }
        public string Netduedatesymbol { get; set; }
        public string Offsettaccounttype { get; set; }
        public string Offsettingacctno { get; set; }
        public string Order { get; set; }
        public string Parkedby { get; set; }
        public string PaymentBlock { get; set; }
        public Nullable<System.DateTime> Paymentdate { get; set; }
        public string PaymentMethod { get; set; }
        public string Paymentorder { get; set; }
        public string Paymentreference { get; set; }
        public string Paymentsent { get; set; }
        public string Plant { get; set; }
        public string Pmntcardlineitem { get; set; }
        public string Pmntcurrency { get; set; }
        public string Pmtmethsupplement { get; set; }
        public string PostingPeriod { get; set; }
        public string Processor { get; set; }
        public string ProfitCenter { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Reasoncode { get; set; }
        public string Refkeyheader2 { get; set; }
        public string Referencekey1 { get; set; }
        public string Referencekey2 { get; set; }
        public string Referencekey3 { get; set; }
        public string RelatedInvIsCustomerDisputed { get; set; }
        public string Reverseclearing { get; set; }
        public string Reversedwith { get; set; }
        public string SalesDocument { get; set; }
        public string SalesDocumentItem { get; set; }
        public string ScheduleLineNumber { get; set; }
        public string SectionCode { get; set; }
        public string Settlementrun { get; set; }
        public Nullable<double> Sortkey { get; set; }
        public string SpGLtranstype { get; set; }
        public string SpecialGLind { get; set; }
        public string Status { get; set; }
        public string Subnumber { get; set; }
        public string TermsofPayment { get; set; }
        public string Text { get; set; }
        public string TextforPriority { get; set; }
        public string TextID { get; set; }
        public string Textsexist { get; set; }
        public Nullable<double> TimeofEntry { get; set; }
        public string TradingPartner { get; set; }
        public string Transaction { get; set; }
        public string Username { get; set; }
        public Nullable<double> Valuatedamount { get; set; }
        public Nullable<double> Valuatedamtloccurr3 { get; set; }
        public Nullable<double> Valuatedamtloccurr2 { get; set; }
        public Nullable<System.DateTime> Valuedate { get; set; }
        public string Vendor { get; set; }
        public string WBSelement { get; set; }
        public string Yearmonth { get; set; }
    }
}
