//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustMaster
    {
        public int CID { get; set; }
        public string CUSTID { get; set; }
        public string CUSTNAME { get; set; }
        public string Name_2 { get; set; }
        public string City { get; set; }
        public Nullable<double> POCODE { get; set; }
        public string Dflag { get; set; }
        public string YGSCUSTID { get; set; }
    }
}
