//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWDEPENTRY
    {
        public decimal EID { get; set; }
        public Nullable<decimal> DEPID { get; set; }
        public Nullable<int> CUSTID { get; set; }
        public string CUSTNAME { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string INVNO { get; set; }
        public string INVDETAILS { get; set; }
        public string CHQNO { get; set; }
        public string CHQDATE { get; set; }
        public string CLEARING { get; set; }
        public string DIVISION { get; set; }
        public string SALES { get; set; }
        public string PMGH { get; set; }
        public string JOBCODE { get; set; }
        public Nullable<decimal> LD { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> BC { get; set; }
        public Nullable<decimal> OD { get; set; }
        public string JOB { get; set; }
        public string PayType { get; set; }
        public string DFLAG { get; set; }
        public string CLEAR { get; set; }
        public string NONADJUST { get; set; }
        public string ADJUST { get; set; }
        public string ERROR_MSG { get; set; }
        public Nullable<decimal> EXCESS { get; set; }
        public Nullable<decimal> PENALTY { get; set; }
        public Nullable<decimal> PBG { get; set; }
        public Nullable<decimal> RETENTION { get; set; }
        public Nullable<decimal> SEC_DEPOSIT { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public string Remark { get; set; }
    }
}
