//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWDEPMAIN
    {
        public decimal DEPID { get; set; }
        public string DEPOSITNO { get; set; }
        public string EMPNO { get; set; }
        public Nullable<System.DateTime> DEPOSITDATE { get; set; }
        public Nullable<System.DateTime> CURDATE { get; set; }
        public int REGID { get; set; }
        public int BID { get; set; }
        public string DFLAG { get; set; }
        public Nullable<decimal> ID { get; set; }
    }
}
