//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegMaster
    {
        public int RegID { get; set; }
        public string Region { get; set; }
        public string Region_short { get; set; }
        public string CName { get; set; }
        public string Dflag { get; set; }
    }
}
