//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Login_Name { get; set; }
        public string usr_Password { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string usr_Title { get; set; }
        public Nullable<long> usr_Mobile { get; set; }
        public Nullable<long> usr_Phone { get; set; }
        public string usr_Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string DeleteFlag { get; set; }
        public Nullable<decimal> EmpID { get; set; }
        public string EmpName { get; set; }
        public string Department { get; set; }
        public string EMail { get; set; }
        public string Office { get; set; }
    }
}
