//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceModels.FinanceEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public int UserID { get; set; }
        public int EmpID { get; set; }
        public string LoginID { get; set; }
        public string EmpName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Department { get; set; }
        public string EMail { get; set; }
        public string Office { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string DeleteFlag { get; set; }
    }
}
